import React, { useState, useEffect, useRef } from "react";
import "./Salary.css";
import {
  FaWallet,
  FaArrowDown,
  FaMoneyBillWave,
  FaCreditCard,
  FaCalendarAlt,
  FaDownload,
  FaCheckCircle,
  FaFileInvoice,
  FaChartLine,
  FaChevronRight,
  FaChevronDown,
  FaChevronLeft,
  FaTimes,
} from "react-icons/fa";
import "./Salary.css";

const salaryData = {
  2026: [
    {
      month: "August 2026",
      gross: 42000,
      deduction: 7000,
      net: 35000,
      status: "Paid",
      date: "31 Aug 2026",
    },
    {
      month: "July 2026",
      gross: 42000,
      deduction: 7000,
      net: 35000,
      status: "Paid",
      date: "31 Jul 2026",
    },
    {
      month: "June 2026",
      gross: 41000,
      deduction: 6500,
      net: 34500,
      status: "Paid",
      date: "30 Jun 2026",
    },
    {
      month: "May 2026",
      gross: 41000,
      deduction: 6500,
      net: 34500,
      status: "Paid",
      date: "31 May 2026",
    },
    {
      month: "April 2026",
      gross: 40000,
      deduction: 6200,
      net: 33800,
      status: "Paid",
      date: "30 Apr 2026",
    },
  ],
  2025: [
    {
      month: "December 2025",
      gross: 39000,
      deduction: 6000,
      net: 33000,
      status: "Paid",
      date: "31 Dec 2025",
    },
    {
      month: "November 2025",
      gross: 39000,
      deduction: 6000,
      net: 33000,
      status: "Paid",
      date: "30 Nov 2025",
    },
    {
      month: "October 2025",
      gross: 38000,
      deduction: 5800,
      net: 32200,
      status: "Paid",
      date: "31 Oct 2025",
    },
  ],
};

function Salary() {
  const [year, setYear] = useState(2026);
  const [trend, setTrend] = useState("6");
  const [showMessage, setShowMessage] = useState(false);
  const [showSalaryStructure, setShowSalaryStructure] = useState(false);
  const salaryStructure = () => {
  setShowSalaryStructure(true);
};

  const currentData = salaryData[year] || [];

  const gross = currentData[0]?.gross || 0;
  const deduction = currentData[0]?.deduction || 0;
  const net = currentData[0]?.net || 0;

  const formatMoney = (amount) => {
    return `₹${amount.toLocaleString("en-IN")}`;
  };

  // Download payslip
  const downloadPayslip = (month, netSalary) => {
    const content = `
EMPLOYEE SALARY PAYSLIP
-----------------------
Employee: Mayank Panse
Month: ${month}

Gross Salary: ${formatMoney(gross)}
Total Deductions: ${formatMoney(deduction)}
Net Salary: ${formatMoney(netSalary)}

Payment Status: Paid
Generated by Employee Management System
    `;

    const blob = new Blob([content], {
      type: "text/plain",
    });

    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = `${month}-Payslip.txt`;
    link.click();

    window.URL.revokeObjectURL(url);

    setShowMessage(true);

    setTimeout(() => {
      setShowMessage(false);
    }, 2500);
  };

  // Download Form 16
  const downloadForm16 = () => {
    const content = `
FORM 16
--------
Employee Name: Mayank Panse
Assessment Year: ${year + 1}

Annual CTC: ₹5,04,000
Annual Gross Salary: ₹5,04,000
Total Deductions: ₹84,000
Net Salary: ₹4,20,000

This is a generated employee document.
    `;

    const blob = new Blob([content], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `Form-16-${year}.txt`;
    link.click();

    URL.revokeObjectURL(url);
  };

  // View all payslips
  const viewAllPayslips = () => {
    document
      .getElementById("payslip-history")
      ?.scrollIntoView({ behavior: "smooth" });
  };

  // Change year
  const changeYear = (value) => {
    setYear(Number(value));
  };

  return (
    <div className="salary-page">

      {/* Notification */}
      {showMessage && (
        <div className="salary-toast">
          <FaCheckCircle />
          Payslip downloaded successfully
          <button onClick={() => setShowMessage(false)}>
            <FaTimes />
          </button>
        </div>
      )}

      {/* Header */}
      <div className="salary-header">
        <div>
          <h1>Salary & Payslips</h1>
          <p>View your salary details, payslips and payment history</p>
        </div>

        <div className="salary-year">
          <FaCalendarAlt />

          <select
            value={year}
            onChange={(e) => changeYear(e.target.value)}
          >
            <option value="2026">Year 2026</option>
            <option value="2025">Year 2025</option>
          </select>

          <FaChevronDown />
        </div>
      </div>

      {/* Summary Cards */}
      <div className="salary-cards">

        <div className="salary-card">
          <div className="salary-icon purple">
            <FaWallet />
          </div>

          <div>
            <span>Gross Salary</span>
            <h2>{formatMoney(gross)}</h2>
            <small>August {year}</small>
          </div>
        </div>

        <div className="salary-card">
          <div className="salary-icon orange">
            <FaArrowDown />
          </div>

          <div>
            <span>Total Deductions</span>
            <h2>{formatMoney(deduction)}</h2>
            <small>This Month</small>
          </div>
        </div>

        <div className="salary-card">
          <div className="salary-icon green">
            <FaMoneyBillWave />
          </div>

          <div>
            <span>Net Salary</span>
            <h2>{formatMoney(net)}</h2>
            <small>Take Home</small>
          </div>
        </div>

        <div className="salary-card">
          <div className="salary-icon blue">
            <FaCreditCard />
          </div>

          <div>
            <span>Payment Status</span>

            <h2 className="paid-text">
              Paid <FaCheckCircle />
            </h2>

            <small>31 Aug {year}</small>
          </div>
        </div>

      </div>

      {/* Main Grid */}
      <div className="salary-main">

        {/* Earnings */}
        <div className="salary-box earnings-box">

          <div className="salary-column">
            <h3>Earnings</h3>

            <div className="salary-row">
              <span>Basic Salary</span>
              <b>₹30,000</b>
            </div>

            <div className="salary-row">
              <span>House Rent Allowance (HRA)</span>
              <b>₹6,000</b>
            </div>

            <div className="salary-row">
              <span>Special Allowance</span>
              <b>₹4,000</b>
            </div>

            <div className="salary-row">
              <span>Other Allowance</span>
              <b>₹2,000</b>
            </div>

            <div className="salary-total earning-total">
              <span>Gross Salary</span>
              <b>{formatMoney(gross)}</b>
            </div>
          </div>

          {/* Deductions */}
          <div className="salary-column">

            <h3 className="deduction-title">Deductions</h3>

            <div className="salary-row">
              <span>Provident Fund (PF)</span>
              <b>₹3,600</b>
            </div>

            <div className="salary-row">
              <span>Professional Tax</span>
              <b>₹200</b>
            </div>

            <div className="salary-row">
              <span>ESI</span>
              <b>₹1,200</b>
            </div>

            <div className="salary-row">
              <span>Other Deduction</span>
              <b>₹2,000</b>
            </div>

            <div className="salary-total deduction-total">
              <span>Total Deductions</span>
              <b>{formatMoney(deduction)}</b>
            </div>

          </div>

        </div>

        {/* Salary Overview Card */}
        <div className="salary-box net-box">

          <h4>{year === 2026 ? "August 2026" : "December 2025"}</h4>

          <div className="big-net">
            ₹{net.toLocaleString("en-IN")}
          </div>

          <span>Net Salary</span>

          <div className="net-line"></div>

          <div className="paid-badge">
            <FaCheckCircle /> Salary Paid
          </div>

          <p>Paid on: 31 Aug {year}</p>

          <button
            className="download-main"
            onClick={() =>
              downloadPayslip(
                currentData[0]?.month || "Salary",
                net
              )
            }
          >
            <FaDownload />
            Download Payslip
          </button>

        </div>

      </div>

      {/* Bottom Grid */}
      <div className="salary-bottom">

        {/* Salary Trend */}
        <div className="salary-box trend-box">

          <div className="box-heading">
            <div>
              <h3>Salary Trend</h3>
              <span>(Net Salary)</span>
            </div>

            <select
              value={trend}
              onChange={(e) => setTrend(e.target.value)}
            >
              <option value="6">Last 6 Months</option>
              <option value="12">Last 12 Months</option>
            </select>
          </div>

          <div className="chart">

            <div className="chart-y">
              <span>₹36K</span>
              <span>₹35K</span>
              <span>₹34K</span>
              <span>₹33K</span>
              <span>₹32K</span>
            </div>

            <div className="chart-area">

              <div className="chart-line">
                <span style={{ left: "5%", bottom: "35%" }}>
                  ₹33,500
                </span>

                <span style={{ left: "25%", bottom: "45%" }}>
                  ₹33,800
                </span>

                <span style={{ left: "45%", bottom: "58%" }}>
                  ₹34,200
                </span>

                <span style={{ left: "65%", bottom: "70%" }}>
                  ₹34,500
                </span>

                <span style={{ left: "82%", bottom: "84%" }}>
                  ₹35,000
                </span>

                <span style={{ left: "96%", bottom: "84%" }}>
                  ₹35,000
                </span>

                <div className="line"></div>
              </div>

              <div className="chart-months">
                <span>Mar 2026</span>
                <span>Apr 2026</span>
                <span>May 2026</span>
                <span>Jun 2026</span>
                <span>Jul 2026</span>
                <span>Aug 2026</span>
              </div>

            </div>

          </div>

        </div>

        {/* Earnings Distribution */}
        <div className="salary-box distribution-box">

          <h3>Earnings Distribution</h3>

          <div className="distribution-content">

            <div className="donut">
              <div>
                <b>₹42,000</b>
                <span>Gross Salary</span>
              </div>
            </div>

            <div className="distribution-list">

              <p>
                <i className="dot basic"></i>
                Basic Salary
                <b>71.4%</b>
                <strong>₹30,000</strong>
              </p>

              <p>
                <i className="dot hra"></i>
                HRA
                <b>14.3%</b>
                <strong>₹6,000</strong>
              </p>

              <p>
                <i className="dot allowance"></i>
                Allowances
                <b>14.3%</b>
                <strong>₹6,000</strong>
              </p>

            </div>

          </div>

        </div>

      </div>

      {/* Payslip History */}
      <div
        className="salary-box payslip-box"
        id="payslip-history"
      >

        <div className="box-heading">
          <h3>Payslip History</h3>
        </div>

        <div className="table-wrapper">

          <table>

            <thead>
              <tr>
                <th>Month</th>
                <th>Gross Salary</th>
                <th>Deductions</th>
                <th>Net Salary</th>
                <th>Status</th>
                <th>Payment Date</th>
                <th>Payslip</th>
              </tr>
            </thead>

            <tbody>

              {currentData.map((item, index) => (

                <tr key={index}>

                  <td>
                    <FaCalendarAlt />
                    {item.month}
                  </td>

                  <td>{formatMoney(item.gross)}</td>

                  <td>{formatMoney(item.deduction)}</td>

                  <td>{formatMoney(item.net)}</td>

                  <td>
                    <span className="status-paid">
                      <FaCheckCircle />
                      {item.status}
                    </span>
                  </td>

                  <td>{item.date}</td>

                  <td>

                    <button
                      className="table-download"
                      onClick={() =>
                        downloadPayslip(
                          item.month,
                          item.net
                        )
                      }
                    >
                      <FaDownload />
                      Download
                    </button>

                  </td>

                </tr>

              ))}

            </tbody>

          </table>

        </div>

        <button
          className="view-payslips"
          onClick={viewAllPayslips}
        >
          View All Payslips
          <FaChevronRight />
        </button>

      </div>

      {/* Right Side Quick Actions */}
      <div className="quick-actions">

        <h3>Quick Actions</h3>

        <button onClick={downloadForm16}>
          <div className="quick-icon green">
            <FaFileInvoice />
          </div>

          <div>
            <b>Download Form 16</b>
            <small>View and download your Form 16</small>
          </div>

          <FaChevronRight />
        </button>

        <button onClick={salaryStructure}>
          <div className="quick-icon purple">
            <FaChartLine />
          </div>

          <div>
            <b>Salary Structure</b>
            <small>View your salary structure & details</small>
          </div>

          <FaChevronRight />
        </button>

      </div>
      {showSalaryStructure && (
  <div
    className="salary-modal-overlay"
    onClick={() => setShowSalaryStructure(false)}
  >
    <div
      className="salary-modal"
      onClick={(e) => e.stopPropagation()}
    >
      <div className="salary-modal-header">
        <div>
          <h2>Salary Structure</h2>
          <p>Your current salary structure and details</p>
        </div>

        <button
          className="modal-close"
          onClick={() => setShowSalaryStructure(false)}
        >
          <FaTimes />
        </button>
      </div>

      <div className="salary-modal-content">

        <div className="modal-salary-row">
          <span>Basic Salary</span>
          <strong>₹30,000</strong>
        </div>

        <div className="modal-salary-row">
          <span>House Rent Allowance (HRA)</span>
          <strong>₹6,000</strong>
        </div>

        <div className="modal-salary-row">
          <span>Special Allowance</span>
          <strong>₹4,000</strong>
        </div>

        <div className="modal-salary-row">
          <span>Other Allowance</span>
          <strong>₹2,000</strong>
        </div>

        <div className="modal-divider"></div>

        <div className="modal-salary-row total">
          <span>Gross Salary</span>
          <strong>₹42,000</strong>
        </div>

        <div className="modal-salary-row deduction">
          <span>Total Deductions</span>
          <strong>₹7,000</strong>
        </div>

        <div className="modal-net">
          <span>Net Salary</span>
          <strong>₹35,000</strong>
        </div>

      </div>

      <div className="salary-modal-footer">
        <button
          onClick={() => setShowSalaryStructure(false)}
          className="modal-cancel"
        >
          Close
        </button>
      </div>
    </div>
  </div>
)}

    </div>
  );
}

export default Salary;